//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiteneLoader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int User_Num {
            get {
                return ((int)(this["User_Num"]));
            }
            set {
                this["User_Num"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User_0")]
        public string Name_0 {
            get {
                return ((string)(this["Name_0"]));
            }
            set {
                this["Name_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User_1")]
        public string Name_1 {
            get {
                return ((string)(this["Name_1"]));
            }
            set {
                this["Name_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User_2")]
        public string Name_2 {
            get {
                return ((string)(this["Name_2"]));
            }
            set {
                this["Name_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User_3")]
        public string Name_3 {
            get {
                return ((string)(this["Name_3"]));
            }
            set {
                this["Name_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User_4")]
        public string Name_4 {
            get {
                return ((string)(this["Name_4"]));
            }
            set {
                this["Name_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password_0 {
            get {
                return ((string)(this["Password_0"]));
            }
            set {
                this["Password_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password_1 {
            get {
                return ((string)(this["Password_1"]));
            }
            set {
                this["Password_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password_2 {
            get {
                return ((string)(this["Password_2"]));
            }
            set {
                this["Password_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password_3 {
            get {
                return ((string)(this["Password_3"]));
            }
            set {
                this["Password_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password_4 {
            get {
                return ((string)(this["Password_4"]));
            }
            set {
                this["Password_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mitene.us/f/")]
        public string Shared_URL_0 {
            get {
                return ((string)(this["Shared_URL_0"]));
            }
            set {
                this["Shared_URL_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mitene.us/f/")]
        public string Shared_URL_1 {
            get {
                return ((string)(this["Shared_URL_1"]));
            }
            set {
                this["Shared_URL_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mitene.us/f/")]
        public string Shared_URL_2 {
            get {
                return ((string)(this["Shared_URL_2"]));
            }
            set {
                this["Shared_URL_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mitene.us/f/")]
        public string Shared_URL_3 {
            get {
                return ((string)(this["Shared_URL_3"]));
            }
            set {
                this["Shared_URL_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mitene.us/f/")]
        public string Shared_URL_4 {
            get {
                return ((string)(this["Shared_URL_4"]));
            }
            set {
                this["Shared_URL_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Mitene_Data")]
        public string Storage_Folder_0 {
            get {
                return ((string)(this["Storage_Folder_0"]));
            }
            set {
                this["Storage_Folder_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Mitene_Data")]
        public string Storage_Folder_1 {
            get {
                return ((string)(this["Storage_Folder_1"]));
            }
            set {
                this["Storage_Folder_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Mitene_Data")]
        public string Storage_Folder_2 {
            get {
                return ((string)(this["Storage_Folder_2"]));
            }
            set {
                this["Storage_Folder_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Mitene_Data")]
        public string Storage_Folder_3 {
            get {
                return ((string)(this["Storage_Folder_3"]));
            }
            set {
                this["Storage_Folder_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Mitene_Data")]
        public string Storage_Folder_4 {
            get {
                return ((string)(this["Storage_Folder_4"]));
            }
            set {
                this["Storage_Folder_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@YYYY\\MM")]
        public string SubFolder_Type_0 {
            get {
                return ((string)(this["SubFolder_Type_0"]));
            }
            set {
                this["SubFolder_Type_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@YYYY\\MM")]
        public string SubFolder_Type_1 {
            get {
                return ((string)(this["SubFolder_Type_1"]));
            }
            set {
                this["SubFolder_Type_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@YYYY\\MM")]
        public string SubFolder_Type_2 {
            get {
                return ((string)(this["SubFolder_Type_2"]));
            }
            set {
                this["SubFolder_Type_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@YYYY\\MM")]
        public string SubFolder_Type_3 {
            get {
                return ((string)(this["SubFolder_Type_3"]));
            }
            set {
                this["SubFolder_Type_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@YYYY\\MM")]
        public string SubFolder_Type_4 {
            get {
                return ((string)(this["SubFolder_Type_4"]));
            }
            set {
                this["SubFolder_Type_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Login_Cookie_Clear_0 {
            get {
                return ((bool)(this["Login_Cookie_Clear_0"]));
            }
            set {
                this["Login_Cookie_Clear_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Login_Cookie_Clear_1 {
            get {
                return ((bool)(this["Login_Cookie_Clear_1"]));
            }
            set {
                this["Login_Cookie_Clear_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Login_Cookie_Clear_2 {
            get {
                return ((bool)(this["Login_Cookie_Clear_2"]));
            }
            set {
                this["Login_Cookie_Clear_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Login_Cookie_Clear_3 {
            get {
                return ((bool)(this["Login_Cookie_Clear_3"]));
            }
            set {
                this["Login_Cookie_Clear_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Login_Cookie_Clear_4 {
            get {
                return ((bool)(this["Login_Cookie_Clear_4"]));
            }
            set {
                this["Login_Cookie_Clear_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Finished_Page_Cancel_0 {
            get {
                return ((bool)(this["Finished_Page_Cancel_0"]));
            }
            set {
                this["Finished_Page_Cancel_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Finished_Page_Cancel_1 {
            get {
                return ((bool)(this["Finished_Page_Cancel_1"]));
            }
            set {
                this["Finished_Page_Cancel_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Finished_Page_Cancel_2 {
            get {
                return ((bool)(this["Finished_Page_Cancel_2"]));
            }
            set {
                this["Finished_Page_Cancel_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Finished_Page_Cancel_3 {
            get {
                return ((bool)(this["Finished_Page_Cancel_3"]));
            }
            set {
                this["Finished_Page_Cancel_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Finished_Page_Cancel_4 {
            get {
                return ((bool)(this["Finished_Page_Cancel_4"]));
            }
            set {
                this["Finished_Page_Cancel_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("977167176855,741344068196,537027308733,485355320894,331879840492,195260822059,717" +
            "163229874,448437270311,759605084854,432972386930")]
        public string UserID_List {
            get {
                return ((string)(this["UserID_List"]));
            }
            set {
                this["UserID_List"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("さわべ,山口博司,吉川,鈴木,野作,畑,澤邉農園,北口,山口博司,山口正幸")]
        public string UserName_List {
            get {
                return ((string)(this["UserName_List"]));
            }
            set {
                this["UserName_List"] = value;
            }
        }
    }
}
